sudo: false

language: python
python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - 3.6

env:
  global:
    - LD_PRELOAD=/lib/x86_64-linux-gnu/libSegFault.so
    - SEGFAULT_SIGNALS=all
    - PYTHONUNBUFFERED=True

addons:
  apt:
    sources:
      - mono
      - mono-libtiff-compat
    packages:
      - mono-devel
      - ca-certificates-mono
      - nunit-console

install:
  - pip install six
  - pip install pycparser
  - python setup.py build_ext --inplace

script:
  - export PYTHONPATH=`pwd`:$PYTHONPATH
  - python src/tests/runtests.py
  # - nunit-console src/embed_tests/bin/x64/ReleaseMono/Python.EmbeddingTest.dll

notifications:
  email: false
