sudo: false

language: python
python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - 3.6
  - 3.7-dev

matrix:
  allow_failures:
    - python: 3.7-dev

env:
  global:
    - LD_PRELOAD=/lib/x86_64-linux-gnu/libSegFault.so
    - SEGFAULT_SIGNALS=all
    - PYTHONUNBUFFERED=True
    - CODECOV_ENV=TRAVIS_PYTHON_VERSION

addons:
  apt:
    sources:
      - mono
      - mono-libtiff-compat
    packages:
      - mono-devel
      - ca-certificates-mono

before_install:
  # Set-up dll path for embedded tests
  - PY_LIBDIR=$(python -c 'import sysconfig; print(sysconfig.get_config_var("LIBDIR"))')
  - export LD_LIBRARY_PATH=$PY_LIBDIR:$LD_LIBRARY_PATH

install:
  - pip install --upgrade setuptools # TEMP - due to setuptools 36.2.0 bug
  - pip install --upgrade -r requirements.txt
  - coverage run setup.py install

script:
  - python -m pytest
  - mono ./packages/NUnit.*/tools/nunit3-console.exe src/embed_tests/bin/Python.EmbeddingTest.dll

after_script:
  # Uncomment if need to geninterop, ie. py37 final
  # - python tools/geninterop/geninterop.py

  # Waiting on mono-coverage, SharpCover or xr.Baboon
  - coverage xml -i
  - codecov --file coverage.xml --flags setup_linux

notifications:
  email: false
  slack:
    secure: "UiQdSK1/uNnHl8/gQgfLj/F5JGxtJuaT3QYtKNcw3Ddpr3FX8tfXJ/RjsCsSlRQzDm7AdBAeMzcBQmvH4iRIV2y7qVywLyru5MPiwY4ZjMN6fJK/zaaxetOct9fasIBYzHguNPDAtiBGFh2iK1H1MXTY8rkmU3WZvl18b8EsrP0="
